language: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: B2u4pKlILbxkiAgedtHlaQTt9LwmBs6Nx/0r9O1teAREIVOfvg9t0KqzUajYYFZDR9iu5wmHu0g0djd9zARyL3a9u5lWTvMpmHpgV/cwj49tFdzaQqZV887C7I/V+OelF7qobj4GE91y1PUydOhJdarLaHkQZUR5xBNhKptPVfM094EAH1TRUjd1vxMC6WfWii1C3gSfyUB0qvHNPDAYtRkj2Veby7k4ZDpqs5eWEFS/uW3PaPsO0ke2a3DNmLNnjT91FPQsfVQipOWIf6txjZnu9fZjrInimBBDDkS37O3iQrfnZmD9pN+T8bmFl5GFHUzmxjy+edcJ1hAB6GHsn/DvyIymxWbVG2+pMIWf0itBxb/uYNRTZpHXF26+jCf+/ZRd5hHozhzKFT/M1uBsaGVd6pVygcT2vrDFOLiwcOTDQT5m0SSeK2kGKkXhEP1apUc0H75WXpuOZ9bxWdCxb0BKzb35lcS0MMpRsQ0moOP3bfP5W2koMBCexe22D8w0GrnQydIcgdRVqh8KML6BvE+z+hQvNFcO6poghXIE/jc0qmNIPsV0T9KLieSBKBFlUG0tAT4olUmsdLNdJtENgxqCuVZPx1FEzB0E7olorOicBNMAkHuHOs1VIiq6PROZnQQaaJkitH0qUNCLIt+fjASV716VClp2NxKJL3abPpI=
